package ezsp

import "github.com/conthing/utils/common"

func EzspCallbackDispatch(cb *EzspFrame) {
	common.Log.Debugf("callback:%s", frameIDToName(cb.FrameID))
	switch cb.FrameID {
	case EZSP_NO_CALLBACKS:
	case EZSP_STACK_TOKEN_CHANGED_HANDLER:
	case EZSP_TIMER_HANDLER:
	case EZSP_COUNTER_ROLLOVER_HANDLER:
	case EZSP_CUSTOM_FRAME_HANDLER:
	case EZSP_STACK_STATUS_HANDLER:
	case EZSP_ENERGY_SCAN_RESULT_HANDLER:
	case EZSP_NETWORK_FOUND_HANDLER:
	case EZSP_SCAN_COMPLETE_HANDLER:
	case EZSP_CHILD_JOIN_HANDLER:
	case EZSP_REMOTE_SET_BINDING_HANDLER:
	case EZSP_REMOTE_DELETE_BINDING_HANDLER:
	case EZSP_MESSAGE_SENT_HANDLER:
	case EZSP_POLL_COMPLETE_HANDLER:
	case EZSP_POLL_HANDLER:
	case EZSP_INCOMING_SENDER_EUI64_HANDLER:
	case EZSP_INCOMING_MESSAGE_HANDLER:
	case EZSP_INCOMING_ROUTE_RECORD_HANDLER:
	case EZSP_INCOMING_MANY_TO_ONE_ROUTE_REQUEST_HANDLER:
	case EZSP_INCOMING_ROUTE_ERROR_HANDLER:
	case EZSP_ID_CONFLICT_HANDLER:
	case EZSP_MAC_PASSTHROUGH_MESSAGE_HANDLER:
	case EZSP_MAC_FILTER_MATCH_MESSAGE_HANDLER:
	case EZSP_RAW_TRANSMIT_COMPLETE_HANDLER:
	case EZSP_SWITCH_NETWORK_KEY_HANDLER:
	case EZSP_ZIGBEE_KEY_ESTABLISHMENT_HANDLER:
	case EZSP_TRUST_CENTER_JOIN_HANDLER:
	case EZSP_GENERATE_CBKE_KEYS_HANDLER:
	case EZSP_CALCULATE_SMACS_HANDLER:
	case EZSP_GENERATE_CBKE_KEYS_HANDLER283K1:
	case EZSP_CALCULATE_SMACS_HANDLER283K1:
	case EZSP_DSA_SIGN_HANDLER:
	case EZSP_DSA_VERIFY_HANDLER:
	case EZSP_MFGLIB_RX_HANDLER:
	case EZSP_INCOMING_BOOTLOAD_MESSAGE_HANDLER:
	case EZSP_BOOTLOAD_TRANSMIT_COMPLETE_HANDLER:
	case EZSP_ZLL_NETWORK_FOUND_HANDLER:
	case EZSP_ZLL_SCAN_COMPLETE_HANDLER:
	case EZSP_ZLL_ADDRESS_ASSIGNMENT_HANDLER:
	case EZSP_ZLL_TOUCH_LINK_TARGET_HANDLER:
	case EZSP_RF4CE_INCOMING_MESSAGE_HANDLER:
	case EZSP_RF4CE_MESSAGE_SENT_HANDLER:
	case EZSP_RF4CE_DISCOVERY_COMPLETE_HANDLER:
	case EZSP_RF4CE_DISCOVERY_REQUEST_HANDLER:
	case EZSP_RF4CE_DISCOVERY_RESPONSE_HANDLER:
	case EZSP_RF4CE_AUTO_DISCOVERY_RESPONSE_COMPLETE_HANDLER:
	case EZSP_RF4CE_PAIR_COMPLETE_HANDLER:
	case EZSP_RF4CE_PAIR_REQUEST_HANDLER:
	case EZSP_RF4CE_UNPAIR_HANDLER:
	case EZSP_RF4CE_UNPAIR_COMPLETE_HANDLER:
	default:
	}
}
